#! /bin/sh

. "$HOME/.cache/wal/colors.sh"
wal -R
sxhkd &
dunst &
~/.fehbg & 
~/.config/polybar/launch.sh &
xset r rate 250 60 &
picom --experimental-backends &
pidof bspswallow || bspswallow &

bspc monitor -d code web files processes music sms 7 8 9

# Mouse setings
bspc config pointer_modifier mod4
bspc config focus_follows_pointer true
bspc config pointer_follows_focus true
bspc config pointer_action3 resize_side
bspc config pointer_action2 resize_corner
bspc config pointer_action1 move

bspc config border_width         4
bspc config window_gap          12
bspc config top_padding		28
bspc config bottom_padding	28

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Zathura state=tiled

# Set the border colors.
bspc config normal_border_color "$color0"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color3"
bspc config presel_feedback_color "$color1"

# Terminate already running programs
killall -q sxkhd
killall -q bspwmrc
killall -q bspswallo

# Wait until the processes have been shut down
while pgrep -u $UID -x sxhkd >dev/null; do sleep 1; done
while pgrep -u $UID -x bspwmrc>dev/null; do sleep 1; done
while pgrep -u $UID -x bspswallow>dev/null; do sleep 1; done

# Launch programs
sxhkd
bspwmrc
bspswallow
